name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

  workflow_call:

jobs:
  test-db:
    runs-on: ubuntu-latest
    steps:
      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '11'
      - name: Check database connection
        run: |
          docker run --rm --network host postgres psql -h localhost -U postgres -c "SELECT 1"
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - run: chmod +x gradlew
      - run: ./gradlew build

