name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

  workflow_call:

jobs:
#  test-db:
#    runs-on: ubuntu-latest
#    services:
#      postgres:
#        image: postgres:latest
#        env:
#          POSTGRES_USER: postgres
#          POSTGRES_PASSWORD: password
#          POSTGRES_DB: testdb
#        ports:
#          - 5432:5432
#        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v2
#
#      - name: Wait for PostgreSQL to start
#        run: sleep 10
#
#      - name: Check database connection
#        run: |
#          psql -h 5432 -U postgres -d testdb -c "SELECT 1"
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - run: chmod +x gradlew
      - run: ./gradlew build

