name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

  workflow_call:

jobs:
  test-db:
    runs-on: ubuntu-latest
    steps:
    - name: Set up PostgreSQL
      uses: postgresql/setup-postgres@v2
      with:
        postgresql-version: '13'  
    - name: Check database connection
      run: |
        psql -h localhost -U postgres -c "SELECT 1"
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - run: chmod +x gradlew
      - run: ./gradlew build

