name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

  workflow_call:

jobs:
  Migration_test:
    runs-on: ubuntu-lastest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@4.1.1
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - uses: red-gate/flyway-hub-migration-test@v1
        with:
          projectName: Hiu-plateform-api
          engine: PostgreSQL (v13.2)
          migrationDirs: src/main/resources/db/migration
      - run: chmod +x gradlew
      - run: ./gradlew build

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - run: chmod +x gradlew
      - run: ./gradlew build

