name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

  workflow_call:

jobs:
  Setup_jdk:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'corretto'
  migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout/@v4.1.1
      - uses: red-gate/flyway-hub-migration-test@v4
        with:
          projectName: hui-plateforme-api
          engine: postgres-12
          migrationDirs: src/main/resources/db/migration  
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - run: chmod +x gradlew
      - run: ./gradlew build
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - run: chmod +x gradlew
      - run: ./gradlew test
env:
  FLYWAYHUB_ACCESS_TOKEN: ${{ secrets.FLYWAY_HUB_ACCESS_TOKEN }}
