name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Run database migrations
        uses: red-gate/flyway-hub-migration-test@v4
        with:
          projectName: hui-plateforme-api
          engine: postgres-12
          migrationDirs: src/main/resources/db/migration
        env:
          FLYWAYHUB_ACCESS_TOKEN: ${{ secrets.FLYWAY_HUB_ACCESS_TOKEN }}

      - name: Build with Gradle
        run: chmod +x gradlew

      - name: Build project
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test